// Generated by CoffeeScript 1.6.3
(function() {
  var bodyParser, directory, express, hbs, logger, path, port, server, staticDir, util;

  express = require("express");

  hbs = require("hbs");

  path = require("path");

  util = require("util");

  server = express();

  port = 4040;

  bodyParser = require('body-parser');

  directory = require('serve-index');

  logger = require('morgan');

  staticDir = require('serve-static');

  server.set("view engine", "hbs");

  server.engine("hbs", hbs.__express);

  server.use(staticDir(__dirname + "/out"));

  server.use(logger("dev"));

  server.use(bodyParser());

  server.get("*", function(req, res) {
    return res.render("index", {
      layout: false
    });
  });

  server.listen(port);

  util.log("Express server instance listening on port " + port);

}).call(this);
