// Generated by CoffeeScript 1.6.3
(function() {
  var Server, exec, execFile, express, expressServer, process, server, spawn;

  express = require("express");

  process = require('child_process');

  spawn = process.spawn;

  exec = process.exec;

  execFile = process.execFile;

  expressServer = express();

  Server = (function() {
    function Server() {}

    Server.prototype.child = null;

    Server.prototype.restart = function() {
      var _this = this;
      spawn("docpad", ["generate"]).on("close", function() {
        return console.log("done: docpad generate");
      });
      return spawn("git", ["pull"]).on('close', function() {
        console.log("done: git pull");
        return spawn("npm", ["install"]).on("close", function() {
          console.log("done: npm install");
          return spawn("coffee", ["-c", "./app.coffee"]).on("close", function() {
            console.log("done: compile app.coffee");
            return spawn('forever', ['stop', _this.app]).on('close', function() {
              console.log("done: killing old child");
              if (_this.child) {
                _this.child.kill();
              }
              return _this.start('app.js');
            });
          });
        });
      });
    };

    Server.prototype.start = function(app) {
      console.log("starting up app...");
      this.app = app;
      this.child = spawn('forever', ['start', this.app]);
      this.child.stdout.setEncoding('utf8');
      this.child.stdout.on('data', function(data) {
        var str;
        str = data.toString();
        console.log(str);
      });
      return this.child.on('close', function(code) {
        console.log('process exit code ' + code);
      });
    };

    return Server;

  })();

  server = new Server;

  server.restart('app.js');

  expressServer.post("/github/callback", function(req, res) {
    res.send(200);
    console.log("Github posthook received");
    return server.restart('app.js');
  });

  expressServer.listen(4030);

}).call(this);
